INSERT INTO REFENTRYPOINT (ID,NAME,PHONE) VALUES (0,'ВСЕ','');
INSERT INTO REFENTRYPOINT (ID,NAME,PHONE) VALUES (1,'Верхняя проходная','');
INSERT INTO REFENTRYPOINT (ID,NAME,PHONE) VALUES (2,'Проходная БДМ № 9','');

COMMIT WORK;
