//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryControl.Resources.Doc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialPermit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MaterialPermit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryControl.Resources.Doc.MaterialPermit", typeof(MaterialPermit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select max(date1) from (select max(modifyDate) as date1 from docMaterialPermit union select max(operationDate) as date1 from docHistory where documentType = &apos;materialPermit&apos; and operation = &apos;delete&apos;).
        /// </summary>
        public static string GetLastDate {
            get {
                return ResourceManager.GetString("GetLastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id from docMaterialPermit where autoPermit = @autoPermit.
        /// </summary>
        public static string GetMaterialPermitId {
            get {
                return ResourceManager.GetString("GetMaterialPermitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from docMaterialPermitLoadList(@id, NULL, NULL, NULL, NULL).
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from docMaterialPermitItem where document = @id.
        /// </summary>
        public static string LoadItemList {
            get {
                return ResourceManager.GetString("LoadItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from docMaterialPermitLoadList(NULL, @unitId, @dateFrom, @dateTo, @userId).
        /// </summary>
        public static string LoadList {
            get {
                return ResourceManager.GetString("LoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update docMaterialPermit set entryFlag = 1, entryPoint = @entryPoint, entryDate = @entryDate, modifier = @userId, modifyDate = current_timestamp where id = @id.
        /// </summary>
        public static string SetEntry {
            get {
                return ResourceManager.GetString("SetEntry", resourceCulture);
            }
        }
    }
}
