//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryControl.Resources.Ref {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Vehicle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vehicle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryControl.Resources.Ref.Vehicle", typeof(Vehicle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from refVehicle where id = @id.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gen_refVehicle_id.
        /// </summary>
        public static string GeneratorName {
            get {
                return ResourceManager.GetString("GeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select name from refVehicleMark m, refVehicle v where m.id = v.vehicleMark and v.id = @id.
        /// </summary>
        public static string GetVehicleMark {
            get {
                return ResourceManager.GetString("GetVehicleMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into refVehicle (id, vehicleMark, licensePlate) values (@id, @vehicleMark, @licensePlate).
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select v.id, v.vehicleMark, m.name as nameMark, v.licensePlate, null as contractor, null as contractorName from refVehicleMark m, refVehicle v where v.id = @id and m.id = v.vehicleMark.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from REFVEHICLELOADLIST(@owner, @mark, @license).
        /// </summary>
        public static string LoadList {
            get {
                return ResourceManager.GetString("LoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from refVehicleMark where id = @id.
        /// </summary>
        public static string MarkDelete {
            get {
                return ResourceManager.GetString("MarkDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gen_refVehicleMark_id.
        /// </summary>
        public static string MarkGeneratorName {
            get {
                return ResourceManager.GetString("MarkGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into refVehicleMark (id, name) values (@id, @name).
        /// </summary>
        public static string MarkInsert {
            get {
                return ResourceManager.GetString("MarkInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from refVehicleMark where id = @id.
        /// </summary>
        public static string MarkLoad {
            get {
                return ResourceManager.GetString("MarkLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from refVehicleMark order by name.
        /// </summary>
        public static string MarkLoadList {
            get {
                return ResourceManager.GetString("MarkLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update refVehicleMark set name = @name where id = @id.
        /// </summary>
        public static string MarkUpdate {
            get {
                return ResourceManager.GetString("MarkUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from refVehicleOwner where id = @id.
        /// </summary>
        public static string OwnerDelete {
            get {
                return ResourceManager.GetString("OwnerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gen_refVehicleOwner_id.
        /// </summary>
        public static string OwnerGeneratorName {
            get {
                return ResourceManager.GetString("OwnerGeneratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into refVehicleOwner (id, vehicle, contractor, dateFrom, dateTo) values (@id, @vehicle, @contractor, @dateFrom, @dateTo).
        /// </summary>
        public static string OwnerInsert {
            get {
                return ResourceManager.GetString("OwnerInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select own.id, own.contractor, cont.shortName as contractorName, dateFrom, dateTo
        ///from refVehicleOwner own, refContractor cont
        ///where cont.id = own.contractor and vehicle = @vehicle
        ///order by dateFrom.
        /// </summary>
        public static string OwnerLoadList {
            get {
                return ResourceManager.GetString("OwnerLoadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update refVehicleOwner set vehicle = @vehicle, contractor = @contractor, dateFrom = @dateFrom, dateTo = @dateTo where id = @id.
        /// </summary>
        public static string OwnerUpdate {
            get {
                return ResourceManager.GetString("OwnerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update refVehicle set vehicleMark = @vehicleMark, licensePlate = @licensePlate where id = @id.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
