//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntryControl.Migrations.Scripts {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class M2017122301 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M2017122301() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntryControl.Migrations.Scripts.M2017122301", typeof(M2017122301).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на alter table REFENTRYPOINTGROUP
        ///add constraint FK_REFENTRYPOINTGROUP
        ///foreign key (ENTRYPOINT)
        ///references REFENTRYPOINT(ID)
        ///on delete CASCADE
        ///on update CASCADE.
        /// </summary>
        internal static string CreateForeignKey {
            get {
                return ResourceManager.GetString("CreateForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на alter table REFENTRYPOINTGROUP
        ///add constraint UNQ_REFENTRYPOINTGROUP
        ///unique (GROUPNAME,ENTRYPOINT).
        /// </summary>
        internal static string CreateIndex {
            get {
                return ResourceManager.GetString("CreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE PROCEDURE SETENTRYPOINTGROUP (
        ///    GROUPNAME VARCHAR(50),
        ///    ENTRYPOINT INTEGER,
        ///    ISINCLUDED SMALLINT)
        ///AS
        ///begin
        ///  /* Procedure Text */
        ///  if (:ISINCLUDED = 1) then
        ///  begin
        ///    update or insert
        ///        into refentrypointgroup
        ///            (groupName, entrypoint)
        ///        values
        ///            (:GROUPNAME, :ENTRYPOINT)
        ///        matching
        ///            (groupName, entryPoint);
        ///  end
        ///  else
        ///  begin
        ///    delete
        ///        from refentrypointgroup
        ///        where groupName = :GROUPNAME
        ///          a [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CreateProcedure {
            get {
                return ResourceManager.GetString("CreateProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE TABLE REFENTRYPOINTGROUP(
        ///    GROUPNAME VARCHAR(50) NOT NULL,
        ///    ENTRYPOINT INTEGER NOT NULL).
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
    }
}
